### PR TITLE
Shakil: commiting changes to GitHub pages. Added Featured content 3

### PR DESCRIPTION
**Pull request by shakilbits**
Auto merge is not possible although i fetched the latest archive  before committing. Please help to merge. Thanks

### CODE REVIEW

**Comment by shakilbits** [comment]
Trying to rebase and commit again

**Review by deepgbits — CHANGES_REQUESTED** [review]
Hi Shakil , 
The githubpage is now deleted with index.html . Please make the changes there

**Comment by shakilbits** [comment]
I have done the needed commits. Please merge as there are no more conflicts

**Comment by deepgbits** [comment]
Create a fresh pull request with index.html only

**Pull request closed without merging**
